### ISSUE TITLE
Sampling period / frequency defined on command line - CLTool

### ISSUE THREAD

**Issue by akobelan** [inertialsense/InertialSenseSDK#10]
Could someone add code to allow for the specification of sampling period / frequency on the command line of CLTool. I'm not into the code base as I should be, but I suspect there is a
quick way to do this and a long way to do this.

**Comment by siddirp** [comment]
Hi @akobelan,
This is a good suggestion. We'll see how quickly we can work this in.

**Comment by akobelan** [comment]
Looking forward to it. Thanks.
