### ISSUE TITLE
Wrong units for message description in EvalTools.

### ISSUE THREAD

**Issue by wonwon0** [inertialsense/InertialSenseSDK#15]
![image](https://user-images.githubusercontent.com/22689509/67409360-7a6f9080-f588-11e9-8b5c-e953a9539fa1.png)

According to user manual, the angular rates (i[XX].pqr[YY]) are in rad/s not in degrees/s as shown in the EvalTools message description.

**Comment by wonwon0** [comment]
As i understand, the data is displayed right in the GUI, it's just that it is confusing since when the data is recorded, it is in rad/s.

**Comment by waltjohnson** [comment]
Those values are converted in the EvalTool from radians to degrees for
convenience.  Radians are more computationally friendly and degrees are
easier to read by the user.

You're best off referring to our online docs
<https://docs.inertialsense.com/user-manual/com-protocol/DID-descriptions/> or
data_sets.h in our SDK
<https://github.com/inertialsense/InertialSenseSDK/blob/master/src/data_sets.h>
for a description of the binary messages.

>
