### ISSUE TITLE
How to forward RTCM3 data

### ISSUE THREAD

**Issue by AlexisTM** [inertialsense/InertialSenseSDK#23]
We do not use a local RTK base but the NTRIP servers.

How can we forward the RTCM3 messages through the SDK from an NTRIP server?

**Comment by siddirp** [comment]
The CLTool  program in the SDK demonstrates this well. It essentially calls the function OpenServerConnection() in InertialSense.
The example commands here give an example of connecting using the EvalTool: https://docs.inertialsense.com/user-manual/gnss/rtk_rover/#cltool_1
