### ISSUE TITLE
GPS Time reference

### ISSUE THREAD

**Issue by wynn4** [inertialsense/InertialSenseSDK#4]
Hello,

I noticed in the SDK documentation that within the uDatasets class, the ins2.week attribute is defined as:

> Weeks since January 1st, 1980

Is this correct, or is it actually based on GPS time which is measured from January 06, 1980?

**Comment by waltjohnson** [comment]
You are correct.  GPS time is referenced to the 6th of January, 1980.  We will update our documentation.  Thanks for catching that typo.
