### ISSUE TITLE
Does Not Build in C++17

### ISSUE THREAD

**Issue by lambdaknight** [inertialsense/InertialSenseSDK#7]
The SDK does not build in C++17. Thankfully, it's an easy fix. std::binary_function does not exist in C++17. So, in C++17, in src/ISDataMappings.h:
`struct sCaseInsensitiveCompare : std::binary_function<std::string, std::string, bool>`
should become
`struct sCaseInsensitiveCompare : std::function<bool(std::string, std::string)>`

and

`struct nocase_compare : public std::binary_function<unsigned char, unsigned char, bool>`
should become
`struct nocase_compare : public std::function<bool(unsigned char, unsigned char)>`

and `#include <functional>` needs to be added to the file.

**Comment by jjxtra** [comment]
We are looking at fixing this for next SDK release.

**Comment by jjxtra** [comment]
Please re-open this issue if you still see it in the latest release.
